export type Testament = "Old Testament" | "New Testament";

export type BookMetadata = {
  osis: string;
  name: string;
  apiSlug: string;
  testament: Testament;
  genre: string;
  compositionWindow: string;
  setting: string;
  summary: string;
};

const BOOK_METADATA: BookMetadata[] = [
  { osis: "Gen", name: "Genesis", apiSlug: "genesis", testament: "Old Testament", genre: "Torah", compositionWindow: "Primeval and patriarchal settings; composition is commonly discussed between the second and first millennia BCE.", setting: "Creation, the flood, Babel, and the patriarchs across Mesopotamia, Canaan, and Egypt.", summary: "Genesis frames God as Creator and covenant-maker, tracing the beginnings of the human story and Israel's family line." },
  { osis: "Exod", name: "Exodus", apiSlug: "exodus", testament: "Old Testament", genre: "Torah", compositionWindow: "Wilderness-era traditions with composition debated across Israel's monarchic and exilic periods.", setting: "Israel's deliverance from Egypt, Sinai covenant, and tabernacle formation.", summary: "Exodus presents redemption, covenant identity, holy presence, and the formation of Israel as God's people." },
  { osis: "Lev", name: "Leviticus", apiSlug: "leviticus", testament: "Old Testament", genre: "Torah", compositionWindow: "Priestly legal material shaped around Israel's worship traditions and likely finalized in the first millennium BCE.", setting: "Priestly instruction at Sinai for sacrifice, purity, and holiness.", summary: "Leviticus shows how a redeemed people are to live in holy fellowship with a holy God." },
  { osis: "Num", name: "Numbers", apiSlug: "numbers", testament: "Old Testament", genre: "Torah", compositionWindow: "Wilderness traditions shaped over time and commonly placed in the first millennium BCE.", setting: "Israel's census, rebellion, wandering, and preparation to enter Canaan.", summary: "Numbers highlights God's faithfulness amid human unbelief and the formation of a new generation." },
  { osis: "Deut", name: "Deuteronomy", apiSlug: "deuteronomy", testament: "Old Testament", genre: "Torah", compositionWindow: "Presented as Moses' final speeches; composition is often associated with late monarchic and exilic editing.", setting: "Moab, just before Israel crosses the Jordan into the land.", summary: "Deuteronomy renews covenant loyalty and calls Israel to love God with heart, soul, and strength." },
  { osis: "Josh", name: "Joshua", apiSlug: "joshua", testament: "Old Testament", genre: "Historical Narrative", compositionWindow: "Settlement traditions likely compiled during Israel's monarchy and later preserved in Deuteronomistic history.", setting: "Conquest and allotment of Canaan after Moses' death.", summary: "Joshua emphasizes covenant fulfillment, divine faithfulness, and the seriousness of covenant obedience." },
  { osis: "Judg", name: "Judges", apiSlug: "judges", testament: "Old Testament", genre: "Historical Narrative", compositionWindow: "Early tribal memories later shaped in the first millennium BCE.", setting: "The tribal era between Joshua and the monarchy.", summary: "Judges portrays the cycle of rebellion, oppression, deliverance, and moral collapse when Israel lacks faithful leadership." },
  { osis: "Ruth", name: "Ruth", apiSlug: "ruth", testament: "Old Testament", genre: "Narrative", compositionWindow: "Set in the judges period, with composition often placed in the monarchic or post-exilic era.", setting: "Bethlehem and Moab during a famine and harvest cycle.", summary: "Ruth shows covenant faithfulness, providence, and the surprising inclusion of a Moabite woman in David's line." },
  { osis: "1Sam", name: "1 Samuel", apiSlug: "1samuel", testament: "Old Testament", genre: "Historical Narrative", compositionWindow: "Material from the rise of monarchy, preserved and edited in the first millennium BCE.", setting: "Transition from judges to monarchy through Samuel, Saul, and David.", summary: "1 Samuel explores kingship under God and the contrast between outward power and covenant-hearted obedience." },
  { osis: "2Sam", name: "2 Samuel", apiSlug: "2samuel", testament: "Old Testament", genre: "Historical Narrative", compositionWindow: "Royal traditions shaped in the monarchic and exilic periods.", setting: "David's reign from Hebron to Jerusalem.", summary: "2 Samuel centers on David's kingdom, covenant promises, and the moral complexity of royal failure." },
  { osis: "1Kgs", name: "1 Kings", apiSlug: "1kings", testament: "Old Testament", genre: "Historical Narrative", compositionWindow: "Part of Deuteronomistic history, shaped around exilic theological reflection.", setting: "Solomon's reign through the divided kingdom and Elijah's ministry.", summary: "1 Kings measures rulers by covenant fidelity and presents prophetic confrontation with idolatry." },
  { osis: "2Kgs", name: "2 Kings", apiSlug: "2kings", testament: "Old Testament", genre: "Historical Narrative", compositionWindow: "Exilic or post-exilic shaping of royal records and prophetic traditions.", setting: "From Elisha's ministry to the falls of Samaria and Jerusalem.", summary: "2 Kings explains exile as covenant judgment while preserving hope through prophetic witness." },
  { osis: "1Chr", name: "1 Chronicles", apiSlug: "1chronicles", testament: "Old Testament", genre: "Historical Narrative", compositionWindow: "Often dated to the post-exilic period, likely fifth or fourth century BCE.", setting: "Genealogies and David's reign retold for a restored community.", summary: "1 Chronicles retells Israel's story to center temple worship, Davidic hope, and covenant continuity." },
  { osis: "2Chr", name: "2 Chronicles", apiSlug: "2chronicles", testament: "Old Testament", genre: "Historical Narrative", compositionWindow: "Post-exilic retelling of Judah's monarchy.", setting: "Solomon through the collapse of Judah, viewed through temple and worship concerns.", summary: "2 Chronicles highlights reform, worship, and the consequences of seeking or forsaking the Lord." },
  { osis: "Ezra", name: "Ezra", apiSlug: "ezra", testament: "Old Testament", genre: "Historical Narrative", compositionWindow: "Persian-period memoir and narrative material, commonly dated to the fifth or fourth century BCE.", setting: "Return from exile, temple rebuilding, and covenant renewal in Jerusalem.", summary: "Ezra focuses on restoration through worship, Scripture, and covenant separation unto God." },
  { osis: "Neh", name: "Nehemiah", apiSlug: "nehemiah", testament: "Old Testament", genre: "Historical Narrative", compositionWindow: "Persian-period memoir material likely finalized in the post-exilic era.", setting: "Rebuilding Jerusalem's walls and reforming community life.", summary: "Nehemiah blends practical leadership with covenant reform for a vulnerable restored people." },
  { osis: "Esth", name: "Esther", apiSlug: "esther", testament: "Old Testament", genre: "Narrative", compositionWindow: "Persian court setting with later Jewish literary shaping, often dated to the fourth or third century BCE.", setting: "Diaspora Jews in the Persian Empire under Xerxes I.", summary: "Esther portrays providential deliverance when God's name is hidden but his preserving care is active." },
  { osis: "Job", name: "Job", apiSlug: "job", testament: "Old Testament", genre: "Wisdom", compositionWindow: "Difficult to date; often placed between the patriarchal imagination and first-millennium wisdom reflection.", setting: "An ancient wisdom drama about suffering, justice, and divine speech.", summary: "Job wrestles with innocent suffering and the limits of human attempts to explain God." },
  { osis: "Ps", name: "Psalms", apiSlug: "psalms", testament: "Old Testament", genre: "Poetry and Worship", compositionWindow: "Collected across many centuries from Davidic, temple, royal, exilic, and post-exilic settings.", setting: "Israel's prayer book for lament, praise, thanksgiving, and kingship hope.", summary: "Psalms teaches God's people to sing theology, grief, trust, repentance, and hope." },
  { osis: "Prov", name: "Proverbs", apiSlug: "proverbs", testament: "Old Testament", genre: "Wisdom", compositionWindow: "Solomonic and later wisdom collections gathered over time, likely finalized in the first millennium BCE.", setting: "Instructional sayings for wise, covenant-shaped living.", summary: "Proverbs links the fear of the Lord with practical wisdom in speech, work, relationships, and justice." },
  { osis: "Eccl", name: "Ecclesiastes", apiSlug: "ecclesiastes", testament: "Old Testament", genre: "Wisdom", compositionWindow: "Commonly dated between the late monarchic and post-exilic periods.", setting: "A reflective meditation on toil, time, mortality, and meaning under the sun.", summary: "Ecclesiastes tests human striving and finds ultimate reverence for God beyond life's vapor." },
  { osis: "Song", name: "Song of Solomon", apiSlug: "songofsolomon", testament: "Old Testament", genre: "Poetry", compositionWindow: "Traditionally linked with Solomon; literary shaping is often placed in the monarchic period or later.", setting: "Love poetry celebrating desire, beauty, and covenant delight.", summary: "Song of Solomon honors embodied love and faithful delight through poetic celebration." },
  { osis: "Isa", name: "Isaiah", apiSlug: "isaiah", testament: "Old Testament", genre: "Prophecy", compositionWindow: "Eighth-century prophetic core with exilic and post-exilic horizons across the completed book.", setting: "Judah from Assyrian pressure through visions of exile and restoration.", summary: "Isaiah binds judgment and hope together around the holiness of God and the coming salvation of Zion." },
  { osis: "Jer", name: "Jeremiah", apiSlug: "jeremiah", testament: "Old Testament", genre: "Prophecy", compositionWindow: "Late seventh to early sixth century BCE, around Judah's collapse and exile.", setting: "Jerusalem and Judah under Babylonian threat.", summary: "Jeremiah announces covenant judgment yet promises a new covenant and future restoration." },
  { osis: "Lam", name: "Lamentations", apiSlug: "lamentations", testament: "Old Testament", genre: "Poetry", compositionWindow: "Closely tied to Jerusalem's destruction in 586 BCE and its aftermath.", setting: "A communal lament over Zion's fall.", summary: "Lamentations gives covenant grief a faithful voice without losing sight of God's mercy." },
  { osis: "Ezek", name: "Ezekiel", apiSlug: "ezekiel", testament: "Old Testament", genre: "Prophecy", compositionWindow: "Exilic ministry from roughly 593 to 571 BCE.", setting: "Babylonian exile among deported Judeans.", summary: "Ezekiel emphasizes God's glory, judgment on false security, and restoration by the Spirit." },
  { osis: "Dan", name: "Daniel", apiSlug: "daniel", testament: "Old Testament", genre: "Apocalyptic Narrative", compositionWindow: "Set in the exile; final form is often dated to the second century BCE.", setting: "Jewish faithfulness under imperial pressure in Babylon and beyond.", summary: "Daniel joins court narratives and apocalyptic visions to call for faithful endurance under worldly empires." },
  { osis: "Hos", name: "Hosea", apiSlug: "hosea", testament: "Old Testament", genre: "Prophecy", compositionWindow: "Eighth century BCE in the northern kingdom's final decades.", setting: "Israel's covenant unfaithfulness before Assyria's rise.", summary: "Hosea uses marriage imagery to expose apostasy and proclaim God's stubborn covenant love." },
  { osis: "Joel", name: "Joel", apiSlug: "joel", testament: "Old Testament", genre: "Prophecy", compositionWindow: "Difficult to date, with proposals ranging from early monarchic to post-exilic.", setting: "A locust crisis becomes a lens for the day of the Lord.", summary: "Joel turns disaster into a summons to repentance and a promise of Spirit outpouring." },
  { osis: "Amos", name: "Amos", apiSlug: "amos", testament: "Old Testament", genre: "Prophecy", compositionWindow: "Mid-eighth century BCE during Israel's prosperity under Jeroboam II.", setting: "Northern kingdom complacency, injustice, and false worship.", summary: "Amos insists that covenant worship without justice is intolerable to God." },
  { osis: "Obad", name: "Obadiah", apiSlug: "obadiah", testament: "Old Testament", genre: "Prophecy", compositionWindow: "Often connected to the aftermath of Jerusalem's fall in the sixth century BCE.", setting: "Judgment on Edom for violence against Judah.", summary: "Obadiah declares that proud hostility toward God's people invites God's reversal." },
  { osis: "Jonah", name: "Jonah", apiSlug: "jonah", testament: "Old Testament", genre: "Prophetic Narrative", compositionWindow: "Traditions tied to eighth-century prophecy, likely written later as theological narrative.", setting: "Israelite prophet sent to Nineveh.", summary: "Jonah exposes the narrowness of human mercy against the wideness of God's compassion." },
  { osis: "Mic", name: "Micah", apiSlug: "micah", testament: "Old Testament", genre: "Prophecy", compositionWindow: "Late eighth century BCE alongside Isaiah.", setting: "Judah and Israel under Assyrian threat.", summary: "Micah balances judgment on corrupt leadership with hope for a ruler from Bethlehem and restored Zion." },
  { osis: "Nah", name: "Nahum", apiSlug: "nahum", testament: "Old Testament", genre: "Prophecy", compositionWindow: "Likely seventh century BCE before Nineveh's fall in 612 BCE.", setting: "Oracle against Assyria's capital.", summary: "Nahum announces divine justice against violent empire and comfort for the oppressed." },
  { osis: "Hab", name: "Habakkuk", apiSlug: "habakkuk", testament: "Old Testament", genre: "Prophecy", compositionWindow: "Late seventh century BCE as Babylon rises.", setting: "A prophet questions God about injustice and coming judgment.", summary: "Habakkuk moves from protest to trust, anchoring faith in God's character amid upheaval." },
  { osis: "Zeph", name: "Zephaniah", apiSlug: "zephaniah", testament: "Old Testament", genre: "Prophecy", compositionWindow: "Josiah's reign, likely late seventh century BCE.", setting: "Judah warned of the day of the Lord before reform or exile.", summary: "Zephaniah warns of judgment but ends with a vision of purified nations and rejoicing restoration." },
  { osis: "Hag", name: "Haggai", apiSlug: "haggai", testament: "Old Testament", genre: "Prophecy", compositionWindow: "Precisely dated to 520 BCE.", setting: "Returned exiles discouraged in rebuilding the temple.", summary: "Haggai calls a restored community to prioritize God's house and trust future glory." },
  { osis: "Zech", name: "Zechariah", apiSlug: "zechariah", testament: "Old Testament", genre: "Prophecy and Apocalyptic Vision", compositionWindow: "Initial visions in 520-518 BCE with later material possibly extending further.", setting: "Post-exilic Jerusalem, temple rebuilding, and messianic hope.", summary: "Zechariah fuels restoration with symbolic visions, priest-king imagery, and future hope." },
  { osis: "Mal", name: "Malachi", apiSlug: "malachi", testament: "Old Testament", genre: "Prophecy", compositionWindow: "Post-exilic period, likely fifth century BCE.", setting: "A weary temple community marked by compromised worship and covenant negligence.", summary: "Malachi confronts cold religion and anticipates the Lord's coming messenger." },
  { osis: "Matt", name: "Matthew", apiSlug: "matthew", testament: "New Testament", genre: "Gospel", compositionWindow: "Commonly dated between the late 50s and 80s CE.", setting: "Jesus' life and teaching presented with deep attention to Israel's Scriptures.", summary: "Matthew presents Jesus as the promised Messiah, teacher-king, and fulfillment of Israel's story." },
  { osis: "Mark", name: "Mark", apiSlug: "mark", testament: "New Testament", genre: "Gospel", compositionWindow: "Often dated in the 60s or early 70s CE.", setting: "A fast-moving account of Jesus' ministry, suffering, and resurrection.", summary: "Mark emphasizes the suffering Son of God whose identity becomes clearest at the cross." },
  { osis: "Luke", name: "Luke", apiSlug: "luke", testament: "New Testament", genre: "Gospel", compositionWindow: "Usually dated between the 60s and 80s CE.", setting: "An orderly account for a broader Greco-Roman audience.", summary: "Luke highlights Jesus as Spirit-anointed Savior for Israel and the nations, with special concern for the marginalized." },
  { osis: "John", name: "John", apiSlug: "john", testament: "New Testament", genre: "Gospel", compositionWindow: "Commonly dated between the 80s and 90s CE.", setting: "A reflective Gospel shaped around signs, discourses, and witness.", summary: "John presents Jesus as the eternal Word who reveals the Father and gives life through belief." },
  { osis: "Acts", name: "Acts", apiSlug: "acts", testament: "New Testament", genre: "Historical Narrative", compositionWindow: "Usually dated alongside Luke in the late first century CE.", setting: "The mission of the risen Christ through the Spirit from Jerusalem to Rome.", summary: "Acts traces the church's expansion and shows the gospel crossing ethnic, geographic, and political boundaries." },
  { osis: "Rom", name: "Romans", apiSlug: "romans", testament: "New Testament", genre: "Epistle", compositionWindow: "Mid-50s CE during Paul's Corinthian period.", setting: "Paul writes to believers in Rome before his hoped-for westward mission.", summary: "Romans gives Paul's fullest account of the gospel, righteousness, Jew-Gentile unity, and transformed life in Christ." },
  { osis: "1Cor", name: "1 Corinthians", apiSlug: "1corinthians", testament: "New Testament", genre: "Epistle", compositionWindow: "Early to mid-50s CE.", setting: "Paul addresses a divided, gifted, morally messy church in Corinth.", summary: "1 Corinthians applies the gospel to church conflict, holiness, worship, resurrection, and love." },
  { osis: "2Cor", name: "2 Corinthians", apiSlug: "2corinthians", testament: "New Testament", genre: "Epistle", compositionWindow: "Mid-50s CE after painful conflict with Corinth.", setting: "Paul defends his ministry and reconciles with a wounded congregation.", summary: "2 Corinthians shows apostolic ministry through weakness, suffering, generosity, and new-covenant glory." },
  { osis: "Gal", name: "Galatians", apiSlug: "galatians", testament: "New Testament", genre: "Epistle", compositionWindow: "Late 40s or early 50s CE.", setting: "Churches pressured to add Torah boundary markers to the gospel.", summary: "Galatians fiercely defends justification by faith and life in the Spirit over legalistic distortion." },
  { osis: "Eph", name: "Ephesians", apiSlug: "ephesians", testament: "New Testament", genre: "Epistle", compositionWindow: "Often dated to Paul's imprisonment in the early 60s CE.", setting: "A church or network of churches learning the cosmic scope of Christ's work.", summary: "Ephesians portrays the church as Christ's reconciled body, built for holiness, unity, and spiritual resistance." },
  { osis: "Phil", name: "Philippians", apiSlug: "philippians", testament: "New Testament", genre: "Epistle", compositionWindow: "Usually associated with Paul's imprisonment in the early 60s CE.", setting: "A beloved church sharing in mission, suffering, and joy.", summary: "Philippians joins joy and humility to Christ-centered endurance and gospel partnership." },
  { osis: "Col", name: "Colossians", apiSlug: "colossians", testament: "New Testament", genre: "Epistle", compositionWindow: "Often dated to Paul's imprisonment in the early 60s CE.", setting: "A church tempted by rival spiritual claims and religious supplements.", summary: "Colossians insists on Christ's supremacy and the sufficiency of union with him." },
  { osis: "1Thess", name: "1 Thessalonians", apiSlug: "1thessalonians", testament: "New Testament", genre: "Epistle", compositionWindow: "Around 50-51 CE.", setting: "A young persecuted church needing encouragement and eschatological clarity.", summary: "1 Thessalonians encourages steadfast holiness, hope, and faithful waiting for Christ's return." },
  { osis: "2Thess", name: "2 Thessalonians", apiSlug: "2thessalonians", testament: "New Testament", genre: "Epistle", compositionWindow: "Early 50s CE if Pauline.", setting: "Follow-up correction around end-times confusion and disorder.", summary: "2 Thessalonians steadies a shaken church with perseverance, judgment, and disciplined faithfulness." },
  { osis: "1Tim", name: "1 Timothy", apiSlug: "1timothy", testament: "New Testament", genre: "Pastoral Epistle", compositionWindow: "Often placed in the mid-60s CE if Pauline.", setting: "Timothy shepherding the church in Ephesus amid false teaching.", summary: "1 Timothy orders church life around sound doctrine, godly leadership, and faithful witness." },
  { osis: "2Tim", name: "2 Timothy", apiSlug: "2timothy", testament: "New Testament", genre: "Pastoral Epistle", compositionWindow: "Often connected with Paul's final imprisonment in the mid-60s CE.", setting: "A final charge to Timothy under pressure.", summary: "2 Timothy urges endurance, doctrinal steadiness, and loyal ministry in the face of suffering." },
  { osis: "Titus", name: "Titus", apiSlug: "titus", testament: "New Testament", genre: "Pastoral Epistle", compositionWindow: "Usually placed in the mid-60s CE.", setting: "Titus organizing Cretan churches amid disorder and false teaching.", summary: "Titus links sound doctrine with visibly good works and stable leadership." },
  { osis: "Phlm", name: "Philemon", apiSlug: "philemon", testament: "New Testament", genre: "Epistle", compositionWindow: "Usually associated with Paul's imprisonment in the early 60s CE.", setting: "A personal appeal concerning Onesimus and Christian reconciliation.", summary: "Philemon displays the gospel's social force through brotherhood, forgiveness, and honor." },
  { osis: "Heb", name: "Hebrews", apiSlug: "hebrews", testament: "New Testament", genre: "Sermonic Epistle", compositionWindow: "Likely before or not long after 70 CE, though debated.", setting: "A pressured community tempted to drift from Christ.", summary: "Hebrews exalts Jesus as the final priestly Son and calls weary believers to persevering faith." },
  { osis: "Jas", name: "James", apiSlug: "james", testament: "New Testament", genre: "Epistle", compositionWindow: "Often dated in the 40s or early 50s CE if linked to James the Lord's brother.", setting: "Diaspora believers learning how wisdom-shaped faith acts in real life.", summary: "James demands integrated obedience, where genuine faith shows itself in speech, justice, and endurance." },
  { osis: "1Pet", name: "1 Peter", apiSlug: "1peter", testament: "New Testament", genre: "Epistle", compositionWindow: "Early to mid-60s CE.", setting: "Scattered believers facing social pressure and suffering.", summary: "1 Peter teaches holy endurance by rooting suffering Christians in their living hope and identity in Christ." },
  { osis: "2Pet", name: "2 Peter", apiSlug: "2peter", testament: "New Testament", genre: "Epistle", compositionWindow: "Often dated in the 60s CE if Petrine, though debated.", setting: "Communities threatened by false teachers and moral collapse.", summary: "2 Peter calls believers to steadfast growth, truthfulness, and confidence in the Lord's coming." },
  { osis: "1John", name: "1 John", apiSlug: "1john", testament: "New Testament", genre: "Epistle", compositionWindow: "Late first century CE.", setting: "Johannine communities disturbed by schism and denial about Jesus.", summary: "1 John ties assurance to right Christology, obedient love, and life in the light." },
  { osis: "2John", name: "2 John", apiSlug: "2john", testament: "New Testament", genre: "Epistle", compositionWindow: "Late first century CE.", setting: "A brief warning to a church household about deceptive teachers.", summary: "2 John pairs love with truth and refuses fellowship with teaching that abandons Christ." },
  { osis: "3John", name: "3 John", apiSlug: "3john", testament: "New Testament", genre: "Epistle", compositionWindow: "Late first century CE.", setting: "Local church tensions around hospitality and authority.", summary: "3 John commends faithful support of gospel workers and confronts self-serving leadership." },
  { osis: "Jude", name: "Jude", apiSlug: "jude", testament: "New Testament", genre: "Epistle", compositionWindow: "Late first century CE, though some argue earlier.", setting: "Believers threatened by corrupt intruders twisting grace.", summary: "Jude calls the church to contend for the faith without surrendering mercy or holiness." },
  { osis: "Rev", name: "Revelation", apiSlug: "revelation", testament: "New Testament", genre: "Apocalyptic Prophecy", compositionWindow: "Commonly dated to the reign of Domitian around 95 CE, though earlier dates are also argued.", setting: "Seven churches in Asia Minor under pressure from empire, compromise, and suffering.", summary: "Revelation unveils Christ's victory, calls for patient witness, and reorients the church around the coming new creation." },
];

const bookMap = new Map(BOOK_METADATA.map((book) => [book.osis, book]));

export function getBookMetadata(osis: string): BookMetadata {
  const book = bookMap.get(osis);

  if (!book) {
    throw new Error(`Unsupported book code "${osis}".`);
  }

  return book;
}

export function getAllBookMetadata() {
  return BOOK_METADATA;
}

export function getNewTestamentBookMetadata() {
  return BOOK_METADATA.filter((book) => book.testament === "New Testament");
}
